import time
import logging
from pathlib import Path
from datetime import datetime
from base_watcher import BaseWatcher


class FileSystemWatcher(BaseWatcher):
    def __init__(self, vault_path: str, watch_folder: str = "Inbox", check_interval: int = 30):
        super().__init__(vault_path, check_interval)
        self.watch_folder = self.vault_path / watch_folder
        self.processed_files = set()
        
        # Initialize with existing files to avoid processing them on first run
        if self.watch_folder.exists():
            for file_path in self.watch_folder.iterdir():
                if file_path.is_file():
                    self.processed_files.add(file_path.name)
    
    def check_for_updates(self) -> list:
        """Check for new files in the watch folder"""
        new_items = []
        
        if not self.watch_folder.exists():
            self.logger.warning(f"Watch folder does not exist: {self.watch_folder}")
            return new_items
            
        for file_path in self.watch_folder.iterdir():
            if file_path.is_file() and file_path.name not in self.processed_files:
                new_items.append({
                    'file_path': file_path,
                    'timestamp': datetime.now(),
                    'size': file_path.stat().st_size
                })
                self.processed_files.add(file_path.name)
                
        return new_items
    
    def create_action_file(self, item) -> Path:
        """Create a .md file in Needs_Action folder for the new item"""
        file_path = item['file_path']
        timestamp = item['timestamp'].strftime("%Y%m%d_%H%M%S")
        
        # Create a unique filename
        action_filename = f"action_{file_path.stem}_{timestamp}.md"
        action_file_path = self.needs_action / action_filename
        
        # Create content for the action file
        content = f"""# New File Detected in Inbox

## File Information
- **Original File**: {file_path.name}
- **Detected At**: {item['timestamp'].isoformat()}
- **Size**: {item['size']} bytes
- **Path**: {file_path}

## Action Required
Please review this file and take appropriate action.

## File Content Preview
```
{self._get_file_preview(file_path)}
```

---
*Automatically generated by FileSystemWatcher at {datetime.now().isoformat()}*
"""
        
        # Write the content to the action file
        with open(action_file_path, 'w', encoding='utf-8') as f:
            f.write(content)
            
        self.logger.info(f"Created action file: {action_file_path}")
        return action_file_path
    
    def _get_file_preview(self, file_path: Path, max_lines: int = 10) -> str:
        """Get a preview of the file content"""
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                lines = []
                for i, line in enumerate(f):
                    if i >= max_lines:
                        lines.append("... [truncated]")
                        break
                    lines.append(line.rstrip())
                return "\n".join(lines)
        except Exception:
            # If we can't read the file as text, return a generic message
            return f"[Non-text file or unreadable content: {file_path.suffix}]"


if __name__ == "__main__":
    # Example usage
    vault_path = Path(__file__).parent  # Assuming the script is in the vault directory
    watcher = FileSystemWatcher(str(vault_path))
    watcher.run()