from base_watcher import BaseWatcher
import requests
import time
from datetime import datetime
import json
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

class LinkedInWatcher(BaseWatcher):
    def __init__(self, vault_path: str, check_interval: int = 600):  # 10 minutes default
        super().__init__(vault_path, check_interval)
        self.access_token = os.getenv('LINKEDIN_ACCESS_TOKEN')
        self.headers = {
            'Authorization': f'Bearer {self.access_token}',
            'Content-Type': 'application/json'
        }
        self.last_activity_time = None

        if not self.access_token:
            raise ValueError("LINKEDIN_ACCESS_TOKEN environment variable not set")

    def check_for_updates(self):
        """Check for new LinkedIn activities (messages, comments, reactions)"""
        try:
            activities = []
            
            # Check for new messages
            messages_url = "https://api.linkedin.com/v2/conversationMessages"
            params = {'q': 'participants', 'participant.urn': 'urn:li:person:(self)'}
            
            if self.last_activity_time:
                params['created_since'] = int(self.last_activity_time.timestamp() * 1000)
            
            response = requests.get(messages_url, headers=self.headers, params=params)
            
            if response.status_code == 200:
                data = response.json()
                for message in data.get('elements', []):
                    activities.append({
                        'type': 'message',
                        'id': message.get('id'),
                        'sender': message.get('from', {}).get('entity'),
                        'text': message.get('text', ''),
                        'timestamp': datetime.fromtimestamp(message.get('createdAt', 0)/1000),
                        'conversation_id': message.get('conversation', {}).get('entity')
                    })
            
            # Update last activity time
            self.last_activity_time = datetime.now()
            
            self.logger.info(f"Found {len(activities)} new LinkedIn activities")
            return activities
            
        except Exception as e:
            self.logger.error(f"Error checking LinkedIn: {e}")
            return []

    def create_action_file(self, activity) -> str:
        """Create a .md file in Needs_Action folder for the new LinkedIn activity"""
        timestamp = activity['timestamp'].strftime("%Y%m%d_%H%M%S")
        
        # Create a unique filename based on activity type and timestamp
        activity_type = activity['type']
        activity_id = activity['id']
        
        action_filename = f"LINKEDIN_{activity_type}_{activity_id}_{timestamp}.md"
        action_file_path = self.needs_action / action_filename

        # Create content for the action file
        content = f"""# New LinkedIn Activity

## Activity Information
- **Type**: {activity['type'].title()}
- **Activity ID**: {activity['id']}
- **Sender**: {activity.get('sender', 'Unknown')}
- **Received**: {activity['timestamp'].isoformat()}
- **Conversation ID**: {activity.get('conversation_id', 'N/A')}

## Content
{activity['text']}

## Action Required
This is a new LinkedIn activity that requires your attention. Please review and take appropriate action.

## Recommended Next Steps
1. Review the full activity in your LinkedIn account
2. Determine if this requires a response
3. If needed, create a Plan.md file to outline your response
4. Move this file to Pending_Approval if human approval is needed

---
*Automatically generated by LinkedInWatcher at {datetime.now().isoformat()}*
"""

        # Write the content to the action file
        with open(action_file_path, 'w', encoding='utf-8') as f:
            f.write(content)

        self.logger.info(f"Created action file: {action_file_path}")
        return str(action_file_path)


if __name__ == "__main__":
    import sys
    from pathlib import Path
    
    # Add the vault directory to the path so we can import the watcher modules
    vault_path = Path(__file__).parent
    sys.path.insert(0, str(vault_path))
    
    # Create and start the LinkedIn watcher
    # It will check for new LinkedIn activities every 10 minutes
    try:
        watcher = LinkedInWatcher(
            vault_path=str(vault_path),
            check_interval=600  # 10 minutes
        )
        
        print("Starting LinkedIn Watcher...")
        print(f"Monitoring LinkedIn for new activities every {watcher.check_interval} seconds")
        print("Note: Requires LINKEDIN_ACCESS_TOKEN environment variable to be set")
        print("Press Ctrl+C to stop the watcher.")
        
        watcher.run()
    except ValueError as e:
        print(f"Error: {e}")
        print("Please set the LINKEDIN_ACCESS_TOKEN environment variable")
        print("You can get this from LinkedIn Developer Portal after creating an app")
    except Exception as e:
        print(f"Unexpected error: {e}")